name: build

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build-macos:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-12, macos-11]
        steps:
            -   uses: actions/checkout@v2
            -   name: build 
                run: |
                    swift --version
                    swift build
    
    build-linux:
        runs-on: ${{ matrix.os.runner }}
        strategy:
            matrix:
                os: 
                    -   runner: ubuntu-20.04
                        prefix: ubuntu2004
                        suffix: ubuntu20.04
                    
                    -   runner: ubuntu-18.04
                        prefix: ubuntu1804
                        suffix: ubuntu18.04
                swift: 
                    -   toolchain:  5.6.2-RELEASE
                        branch:     swift-5.6.2-release
                    -   toolchain:  5.5.3-RELEASE
                        branch:     swift-5.5.3-release
                    -   toolchain:  5.4.3-RELEASE
                        branch:     swift-5.4.3-release
                    -   toolchain:  5.3.3-RELEASE
                        branch:     swift-5.3.3-release
        steps:
            -   uses: actions/checkout@v2
            
            -   name: cache swift toolchains
                uses: actions/cache@v2
                with:
                    path: swift-${{ matrix.swift.toolchain }}.tar.gz
                    key: ${{ matrix.os.runner }}:swift:${{ matrix.swift.toolchain }}
                    
            -   name: cache status
                id:   cache_status
                uses: andstor/file-existence-action@v1
                with:
                    files: swift-${{ matrix.swift.toolchain }}.tar.gz
            
            -   name: download swift toolchain 
                if: steps.cache_status.outputs.files_exists == 'false'
                run: "curl https://download.swift.org/\
                      ${{ matrix.swift.branch }}/\
                      ${{ matrix.os.prefix }}/\
                      swift-${{ matrix.swift.toolchain }}/\
                      swift-${{ matrix.swift.toolchain }}-${{ matrix.os.suffix }}.tar.gz \
                      --output swift-${{ matrix.swift.toolchain }}.tar.gz"
            
            -   name: set up swift
                run: |
                    mkdir -p $GITHUB_WORKSPACE/swift-${{ matrix.swift.toolchain }}
                    tar -xzf swift-${{ matrix.swift.toolchain }}.tar.gz -C $GITHUB_WORKSPACE/swift-${{ matrix.swift.toolchain }} --strip 1
                    echo "$GITHUB_WORKSPACE/swift-${{ matrix.swift.toolchain }}/usr/bin" >> $GITHUB_PATH
            -   name: build
                run: |
                    swift --version
                    swift build 